id = "emoji-completions"
name = "Emoji completions"
version = "1.3.1"
schema_version = 1
authors = ["Anders Höckersten <anders@hockersten.se>"]
description = "Adds the ability to complete emojis by typing ':' followed by the emoji name."
repository = "https://github.com/ahockersten/emoji-completions-zed"

[language_servers.emoji-language-server]
name = "Emoji Language Server"
languages = [
    "Markdown",
    "Plain Text",
    "Git Commit",
    "JSON",
    "JSONC",
    "YAML",
    "TOML",
    "Rust",
    "JavaScript",
    "TypeScript",
    "TSX",
    "Python",
    "Go",
    "C",
    "C++",
    "Java",
    "HTML",
    "CSS",
    "XML",
    "SQL",
    "Shell Script",
    "PHP",
    "Ruby",
    "Swift",
    "Kotlin",
    "Scala",
    "Perl",
    "R",
    "Lua",
    "Clojure",
    "Elixir",
    "Erlang",
    "Haskell",
    "Objective-C",
    "Dart",
    "Groovy",
    "Gradle",
    "Dockerfile",
    "Make",
    "CMake",
    "Diff",
    "CSharp",
    "FSharp",
    "SystemVerilog",
    "VHDL",
    "LaTeX",
    "Typst",
    "reST",
    "AsciiDoc",
    "Svelte",
    "Vue.js",
]
